### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by yupengjim** [fitnr/censusgeocode#11]
Dear provider,

Hi, I'm Yupeng Liu from Columbia Business School. Thanks for providing the census geocoder and it is very useful for our research! However, we encountered an error quite often, which is called the ECONNRESET error when we use python to geocode the addresses. This errors stopped the programs we are running. Attached is the error codes and we greatly appreciate if you know how to solve this issue! Thanks so much!

Best regards,

Yupeng

**Comment by fitnr** [comment]
This error is coming from the Census. Their server sadly isn't always reliable. If you have very large numbers of addresses to geocode, I suggest investigating the [tiger geocoder included with postgis](https://postgis.net/docs/Extras.html).

It's a purposeful design decision to just pass along connection errors, rather than hide them as empty results. You can use error catching in your Python script to track these errors for later retry.
